//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeTV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_side_tree {
            get {
                object obj = ResourceManager.GetObject("application_side_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_in {
            get {
                object obj = ResourceManager.GetObject("arrow_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_out {
            get {
                object obj = ResourceManager.GetObject("arrow_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio decoder device &apos;{0}&apos; not found!.
        /// </summary>
        internal static string AudioDeviceNotFound {
            get {
                return ResourceManager.GetString("AudioDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio renderer device &apos;{0}&apos; not found!.
        /// </summary>
        internal static string AudioRendererDeviceNotFound {
            get {
                return ResourceManager.GetString("AudioRendererDeviceNotFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap book_open {
            get {
                object obj = ResourceManager.GetObject("book_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bug {
            get {
                object obj = ResourceManager.GetObject("bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tree node label.\nThe label cannot be blank.
        /// </summary>
        internal static string CannotRenameChannel {
            get {
                return ResourceManager.GetString("CannotRenameChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update (because the SectionsAndTables filter is not in the graph)!.
        /// </summary>
        internal static string CannotUpdatePidChannel {
            get {
                return ResourceManager.GetString("CannotUpdatePidChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture device device &apos;{0}&apos; not found!.
        /// </summary>
        internal static string CaptureDeviceNotFound {
            get {
                return ResourceManager.GetString("CaptureDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string ChannelXMLFilter {
            get {
                return ResourceManager.GetString("ChannelXMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;This Folder&gt;.
        /// </summary>
        internal static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CodeTV {
            get {
                object obj = ResourceManager.GetObject("CodeTV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CodeTV2 {
            get {
                object obj = ResourceManager.GetObject("CodeTV2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_eject {
            get {
                object obj = ResourceManager.GetObject("control_eject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_eject_blue {
            get {
                object obj = ResourceManager.GetObject("control_eject_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_equalizer_blue {
            get {
                object obj = ResourceManager.GetObject("control_equalizer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_fastforward_blue {
            get {
                object obj = ResourceManager.GetObject("control_fastforward_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_pause {
            get {
                object obj = ResourceManager.GetObject("control_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_pause_blue {
            get {
                object obj = ResourceManager.GetObject("control_pause_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_play {
            get {
                object obj = ResourceManager.GetObject("control_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_play_blue {
            get {
                object obj = ResourceManager.GetObject("control_play_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_repeat {
            get {
                object obj = ResourceManager.GetObject("control_repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_rewind_blue {
            get {
                object obj = ResourceManager.GetObject("control_rewind_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_stop {
            get {
                object obj = ResourceManager.GetObject("control_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_stop_blue {
            get {
                object obj = ResourceManager.GetObject("control_stop_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A que coucou.
        /// </summary>
        internal static string Coucou {
            get {
                return ResourceManager.GetString("Coucou", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap database_save {
            get {
                object obj = ResourceManager.GetObject("database_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_table {
            get {
                object obj = ResourceManager.GetObject("database_table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticon_smile {
            get {
                object obj = ResourceManager.GetObject("emoticon_smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string FileDialogAllFiles {
            get {
                return ResourceManager.GetString("FileDialogAllFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap film {
            get {
                object obj = ResourceManager.GetObject("film", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H264 decoder device &apos;{0}&apos; not found!.
        /// </summary>
        internal static string H264DecoderDeviceNotFound {
            get {
                return ResourceManager.GetString("H264DecoderDeviceNotFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG2 decoder device &apos;{0}&apos; not found!.
        /// </summary>
        internal static string MPEG2DecoderDeviceNotFound {
            get {
                return ResourceManager.GetString("MPEG2DecoderDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewChannelFolder {
            get {
                return ResourceManager.GetString("NewChannelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string NewChannelName {
            get {
                return ResourceManager.GetString("NewChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Channel.
        /// </summary>
        internal static string NoChannel {
            get {
                return ResourceManager.GetString("NoChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has been raised in the plugin &apos;{0}&apos;:\r\n{1}.
        /// </summary>
        internal static string PluginException {
            get {
                return ResourceManager.GetString("PluginException", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording: &apos;{0}&apos;.
        /// </summary>
        internal static string RecordingInFile {
            get {
                return ResourceManager.GetString("RecordingInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0}.
        /// </summary>
        internal static string ScanningChannel {
            get {
                return ResourceManager.GetString("ScanningChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning error.
        /// </summary>
        internal static string ScanningError {
            get {
                return ResourceManager.GetString("ScanningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hz.
        /// </summary>
        internal static string ScanningFrequency {
            get {
                return ResourceManager.GetString("ScanningFrequency", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap shading {
            get {
                object obj = ResourceManager.GetObject("shading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shape_handles {
            get {
                object obj = ResourceManager.GetObject("shape_handles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shape_square {
            get {
                object obj = ResourceManager.GetObject("shape_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shape_square_add {
            get {
                object obj = ResourceManager.GetObject("shape_square_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shape_square_delete {
            get {
                object obj = ResourceManager.GetObject("shape_square_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save the snapshot: &apos;{0}&apos;.
        /// </summary>
        internal static string SnapshotNotSaved {
            get {
                return ResourceManager.GetString("SnapshotNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot saved: &apos;{0}&apos;.
        /// </summary>
        internal static string SnapshotSaved {
            get {
                return ResourceManager.GetString("SnapshotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH_mm_ss.
        /// </summary>
        internal static string SnapShotTimeFormat {
            get {
                return ResourceManager.GetString("SnapShotTimeFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sound {
            get {
                object obj = ResourceManager.GetObject("sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound_add {
            get {
                object obj = ResourceManager.GetObject("sound_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound_delete {
            get {
                object obj = ResourceManager.GetObject("sound_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound_low {
            get {
                object obj = ResourceManager.GetObject("sound_low", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound_mute {
            get {
                object obj = ResourceManager.GetObject("sound_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound_none {
            get {
                object obj = ResourceManager.GetObject("sound_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound1 {
            get {
                object obj = ResourceManager.GetObject("sound1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop1 {
            get {
                object obj = ResourceManager.GetObject("Stop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap television {
            get {
                object obj = ResourceManager.GetObject("television", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap time {
            get {
                object obj = ResourceManager.GetObject("time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner device &apos;{0}&apos; not found!.
        /// </summary>
        internal static string TunerDeviceNotFound {
            get {
                return ResourceManager.GetString("TunerDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH_mm_ss.
        /// </summary>
        internal static string VideoRecorderTimeFormat {
            get {
                return ResourceManager.GetString("VideoRecorderTimeFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wand {
            get {
                object obj = ResourceManager.GetObject("wand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must create a new Channel which will be used as a template for the scanning.\nIf it do not work, check the devices in this template..
        /// </summary>
        internal static string WizardYouMustCreateChannelTemplate {
            get {
                return ResourceManager.GetString("WizardYouMustCreateChannelTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
